// <auto-generated />
using System;
using DebtCalculatorWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DebtCalculatorWebApp.Migrations
{
    [DbContext(typeof(DebtCalculatorWebAppContext))]
    [Migration("20190517021102_Mortgage")]
    partial class Mortgage
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DebtCalculatorWebApp.Models.AutoLoan", b =>
                {
                    b.Property<int>("AutoLoanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AutoLoanAmount");

                    b.Property<double>("AutoLoanApr");

                    b.Property<int>("AutoLoanTime");

                    b.Property<DateTime>("RecordDate");

                    b.HasKey("AutoLoanId");

                    b.ToTable("AutoLoan");
                });

            modelBuilder.Entity("DebtCalculatorWebApp.Models.CreditCardLoan", b =>
                {
                    b.Property<int>("CreditCardLoanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("CreditCardLoanAmount");

                    b.Property<int>("CreditCardLoanTime");

                    b.Property<double>("CreditcardLoanApr");

                    b.Property<DateTime>("RecordDate");

                    b.HasKey("CreditCardLoanId");

                    b.ToTable("CreditCardLoan");
                });

            modelBuilder.Entity("DebtCalculatorWebApp.Models.Mortgage", b =>
                {
                    b.Property<int>("MortgageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("MortgageAmount");

                    b.Property<double>("MortgageApr");

                    b.Property<int>("MortgageTime");

                    b.Property<DateTime>("RecordDate");

                    b.HasKey("MortgageId");

                    b.ToTable("Mortgage");
                });
#pragma warning restore 612, 618
        }
    }
}
