// <auto-generated />
using System;
using DebtCalculatorWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DebtCalculatorWebApp.Migrations
{
    [DbContext(typeof(DebtCalculatorWebAppContext))]
    partial class DebtCalculatorWebAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DebtCalculatorWebApp.Models.AutoLoan", b =>
                {
                    b.Property<int>("AutoLoanId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AutoLoanAmount");

                    b.Property<double>("AutoLoanApr");

                    b.Property<int>("AutoLoanTime");

                    b.Property<DateTime>("RecordDate");

                    b.HasKey("AutoLoanId");

                    b.ToTable("AutoLoan");
                });
#pragma warning restore 612, 618
        }
    }
}
